style:
  tag:
    color: cyan
    width_percentage: 26
    min_width: 20
  comment:
    color: blue
    width_percentage: 42
    min_width: 45
  snippet:
    color: white

cheats:
  paths:
    - ~/.local/share/navi/cheats
    - ~/.config/navi/cheats

finder:
  command: fzf

shell:
  command: zsh
